name: Maven CI

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 25

      - name: Grant execute permission for Maven Wrapper
        run: chmod +x mvnw

      - name: Build and Test with Maven
        run: ./mvnw -B verify --file pom.xml
